# Generated by Django 4.2.10 on 2024-02-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Customer Name'),
        ),
    ]
