# Generated by Django 4.2.10 on 2024-02-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='johndoe@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
